/** End-user documents — completion, generation, view & download (mounted at /api/documents) */
import { Router } from 'express';
import { repo } from '../../db/connection';
import { UserDocument, Template, DocumentSignature } from '../../db/entities';
import { config } from '../../config';
import { asyncHandler, HttpError, missingRequired } from '../../utils/helpers';
import { authRequired } from '../../middleware/auth';
import { logAudit } from '../../middleware/audit';
import { generateFinalDocument, assertTransition } from '../../services/document.service';
import { readObject } from '../../services/storage.service';
import { injectSignatures } from '../../services/handlebars.service';
import { renderWordHtml } from '../../services/worddoc.service';
import { loadOwned } from './documents.routes';

export const documentLifecycleRouter = Router();
documentLifecycleRouter.use(authRequired);

const STALE_MARKUP = /{{#(?:if|each|unless)|class="cond-block"|class="repeat-block"|data-when=/;

async function getRenderedHtml(doc: UserDocument): Promise<string> {
  let html = '';
  if (doc.generatedHtmlKey) {
    try { html = readObject(doc.generatedHtmlKey).toString('utf8'); } catch { html = ''; }
  }
  // Self-heal: stored HTML generated by an older/broken engine may still contain
  // unresolved conditionals/merge tokens — regenerate from the template + answers.
  if (html && STALE_MARKUP.test(html)) html = '';
  if (!html) {
    const template = await repo(Template).findOne({ where: { id: doc.templateId } });
    if (!template) throw new HttpError(404, 'Template not found');
    await generateFinalDocument(doc, template);
    await repo(UserDocument).save(doc);
    html = doc.generatedHtmlKey ? readObject(doc.generatedHtmlKey).toString('utf8') : '';
  }
  // Live-inject collected signatures so drawn / typed / Aadhaar signs are always visible.
  const sigs = await repo(DocumentSignature).find({ where: { documentId: doc.id } });
  return injectSignatures(html, sigs.map((s) => ({
    signerName: s.signerName,
    signerEmail: s.signerEmail,
    signatureType: s.signatureType,
    signatureData: s.signatureData,
    signedAt: s.signedAt,
  })));
}

function assertUnlocked(doc: UserDocument): void {
  if (doc.paymentStatus !== 'paid' && doc.paymentStatus !== 'free') {
    throw new HttpError(402, 'Payment required to access the final document');
  }
}

/** Complete questionnaire → awaiting_payment (paid) or generated (free) */
documentLifecycleRouter.post(
  '/:id/complete',
  asyncHandler(async (req, res) => {
    const doc = await loadOwned(req.user!.id, String(req.params.id));
    if (doc.status !== 'draft') throw new HttpError(400, 'Questionnaire already completed');
    const template = await repo(Template).findOne({ where: { id: doc.templateId } });
    if (!template) throw new HttpError(404, 'Template not found');
    const missing = missingRequired(template.questionnaireSchema, doc.userAnswers ?? {});
    if (missing.length > 0) return res.status(400).json({ error: 'Please answer all required questions', missing });

    if (template.isPaid) {
      assertTransition(doc, 'awaiting_payment');
      doc.expiresAt = new Date(Date.now() + config.signingExpiryDays * 24 * 60 * 60 * 1000);
    } else {
      await generateFinalDocument(doc, template);
      assertTransition(doc, 'generated');
      doc.paymentStatus = 'free';
    }
    await repo(UserDocument).save(doc);
    template.usageCount += 1;
    await repo(Template).save(template);
    await logAudit(req, {
      action: 'Questionnaire Completed', actionCategory: 'document', resourceType: 'document',
      resourceId: doc.id, details: { status: doc.status, template: template.name },
    });
    res.json({ document: doc });
  }),
);

/** Owner regenerate (self-heal) */
documentLifecycleRouter.post(
  '/:id/generate',
  asyncHandler(async (req, res) => {
    const doc = await loadOwned(req.user!.id, String(req.params.id));
    if (!['generated', 'pending_signatures', 'partially_signed', 'fully_executed'].includes(doc.status)) {
      throw new HttpError(400, 'Complete the questionnaire and payment first');
    }
    assertUnlocked(doc);
    const template = await repo(Template).findOne({ where: { id: doc.templateId } });
    if (!template) throw new HttpError(404, 'Template not found');
    await generateFinalDocument(doc, template);
    await repo(UserDocument).save(doc);
    await logAudit(req, { action: 'Document Regenerated', actionCategory: 'document', resourceType: 'document', resourceId: doc.id });
    res.json({ document: doc, message: 'Document regenerated' });
  }),
);

/** Rendered document for in-app view + print-to-PDF */
documentLifecycleRouter.get(
  '/:id/file',
  asyncHandler(async (req, res) => {
    const doc = await loadOwned(req.user!.id, String(req.params.id), true);
    assertUnlocked(doc);
    const html = await getRenderedHtml(doc);
    res.json({ html, title: doc.title, documentNumber: doc.documentNumber, status: doc.status });
  }),
);

/** Download as Word-compatible .doc (PDF via client print view) */
documentLifecycleRouter.get(
  '/:id/download',
  asyncHandler(async (req, res) => {
    const doc = await loadOwned(req.user!.id, String(req.params.id), true);
    assertUnlocked(doc);
    const html = await getRenderedHtml(doc);
    await logAudit(req, { action: 'Document Downloaded', actionCategory: 'document', resourceType: 'document', resourceId: doc.id });
    const safe = doc.title.replace(/[^\w\- ]+/g, '').trim() || 'document';
    res.setHeader('Content-Type', 'application/msword');
    res.setHeader('Content-Disposition', `attachment; filename="${safe}.doc"`);
    // Full Word HTML wrapper — raw fragments opened with Word defaults
    // (US-Letter 1" margins, unstyled headings) and never matched the PDF/DOCX.
    res.send(renderWordHtml(html, doc.title));
  }),
);

/** Download as real .docx (Office Open XML) */
documentLifecycleRouter.get(
  '/:id/docx',
  asyncHandler(async (req, res) => {
    const doc = await loadOwned(req.user!.id, String(req.params.id), true);
    assertUnlocked(doc);
    const html = await getRenderedHtml(doc);
    const { generateDocx } = await import('../../services/docx.service');
    const buffer = await generateDocx(html);
    await logAudit(req, { action: 'Document Downloaded (DOCX)', actionCategory: 'document', resourceType: 'document', resourceId: doc.id });
    const safe = doc.title.replace(/[^\w\- ]+/g, '').trim() || 'document';
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
    res.setHeader('Content-Disposition', `attachment; filename="${safe}.docx"`);
    res.send(buffer);
  }),
);

/** Download as real server-rendered PDF */
documentLifecycleRouter.get(
  '/:id/pdf',
  asyncHandler(async (req, res) => {
    const doc = await loadOwned(req.user!.id, String(req.params.id), true);
    assertUnlocked(doc);
    const html = await getRenderedHtml(doc);
    const { generatePdf } = await import('../../services/pdf.service');
    const buffer = await generatePdf(html, `${doc.title} (${doc.documentNumber})`);
    await logAudit(req, { action: 'Document Downloaded (PDF)', actionCategory: 'document', resourceType: 'document', resourceId: doc.id });
    const safe = doc.title.replace(/[^\w\- ]+/g, '').trim() || 'document';
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safe}.pdf"`);
    res.send(buffer);
  }),
);
